### ISSUE TITLE
Support mesos maintenance primitives

### ISSUE THREAD

**Issue by zmalik** [klarna/eremetic#163]
This is not an issue, but more en enhancement so we can discuss if it makes sense to support mesos maintenance modes.

So a very simple version could be checking the Unavailability during the match of offers, and if it happens to be indefinite or the time now is in between the interval, then reject the offer.

**Comment by alde** [comment]
I think this could make sense.

**Comment by keis** [comment]
I'm not too familiar with the maintenance modes so I will have to read up on it a bit. The simple extra offer check sounds pretty straightforward though.

How the finer details interact with our idea of running short lived tasks I'm not sure. It's short so it is soon going to exit anyway and because of the batch nature of the typical workload we don't want to assume it's useful (or safe) to restart a process from the top.

**Comment by alde** [comment]
I'm more inclined to think "if a node is about to go into maintenance, don't launch new things on it", not so much "move things from it to a new node"

**Comment by zmalik** [comment]
yep exactly! I think we can leave the **inverse offers** out of scope for first iteration. 

So right now it could be pretty simple. If there is an offer with maintenance window in current time, so just decline that offer and if its in future then still accept it.

**Comment by zmalik** [comment]
Hi guys, if somebody was wondering how can we get juice out of this feature and eremetic itself.

We are already using in production eremetic + [deathnode](https://github.com/alanbover/deathnode) to scale up and down the cluster without having a single job failed during the process.

Kudos for you guys for this amazing framework!

**Comment by keis** [comment]
That's really cool, thanks for sharing :)

**Comment by alde** [comment]
That sounds awesome! nice :) 👍
